### ISSUE TITLE
Deeplink für uniswap on https://mintr.synthetix.io

### ISSUE THREAD

**Issue by martinkrung** [Synthetixio/synthetix-exchange#56]
Deeplink of uniswap works like this:

https://uniswap.exchange/swap/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f

There are strange SNX tokens, even with a similar adress:

0xc011a72400e58ecd99ee497cf89e3775d4bd732f

But I think this is more about this: https://uniswap.exchange/swap/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f

If this is not the right place, just forward

**Comment by justinjmoses** [comment]
@martinkrung Our new ProxyERC20 of SNX is 0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f (you can see the code via https://etherscan.io/address/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f#code). It's what we're migrating to for our SNX proxy as the old one (`0xc011a72400e58ecd99ee497cf89e3775d4bd732f`) isn't fully ERC20 compatible, and thus doesn't work with Uniswap, Kyber, etc. 

As you can see - both this and uniswap.exchange are using the same new ProxyERC20 address: https://github.com/Uniswap/uniswap-frontend/blob/beta/src/contexts/Tokens.js#L332-L337 

And, you can validate the addresses are correct via our dev docs: https://developer.synthetix.io/api/docs/deployed-contracts.html
