### ISSUE TITLE
Scroll bars are all ugly if OS is not Mac

### ISSUE THREAD

**Issue by clementbalestrat** [Synthetixio/synthetix-exchange#96]
@bachstatter Do you have experience in styling scrollbar with JS or CSS?

Would be a super nice to have as I feel like a lot of our users are using Windows.

![unknown](https://user-images.githubusercontent.com/690350/72587273-c42e0400-3948-11ea-9abe-5a6783d3f840.png)

**Comment by bachstatter** [comment]
I have done some stuff a bit tricky to get it nice across all browsers and I'm usually not looking at windows 🙈

I can see if I can make it nicer!

**Comment by clementbalestrat** [comment]
Cool! Let's focus on Chrome and Brave for now.
